server:
    address: localhost
    port: 8092
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        show-sql: true
        hibernate:
          ddl-auto: create-drop


